### ISSUE TITLE
Picture Setting Dialog - Errors on numerical fields

### ISSUE THREAD

**Issue by Ganbin** [4d/4D-WritePro-Interface#10]
## Description
When entering a negative value in any numerical field in the Picture Setting Dialog, a 4D error occurs: `wrong value for attribute "marginTop"` for example. 

## How to reproduce
1. Add an image in a 4D document
2. Open the picture picture setting dialog
3. enter a negative value in any numeric field

### Actual result
An error occurs

### Expected result
No error and the previous value reset or 0

**Comment by Roland-Lannuzel** [comment]
Negative values are transformed into positive:  input value :=abs(input value)
