### ISSUE TITLE
[Feature Request] - Select all the field content

### ISSUE THREAD

**Issue by Ganbin** [4d/4D-WritePro-Interface#11]
In the Picture Setting Dialog, when we click on a numerical field, the cursor is set before or after the number. It would be nice if the value would be all selected so we can directly type the new value instead to have to delete the existing value.

Example:
- MarginTop current value : 0
- Click on the field -> cursor is before the 0
- Enter 2
- MarginTop current value : 20

**Comment by Roland-Lannuzel** [comment]
FYI : Not reported on v19R8 (yet)

**Comment by Roland-Lannuzel** [comment]
Reported on v19R8
