### ISSUE TITLE
Typo in german translation Fextfeld -> Textfeld

### ISSUE THREAD

**Issue by ArminDeeg** [4d/4D-WritePro-Interface#16]
Typo in german translation Fextfeld -> Textfeld

![377D60E1-4F64-40A7-A819-7356C211F9F4](https://user-images.githubusercontent.com/6436037/212880797-337bb191-9244-4ab6-b022-4aedc1e8a50f.jpeg)

**Comment by mesopelagique** [comment]
thank you for your report
fixed by 2f452a31ab0168e15d0bf800632ccc209749b5c0
