### ISSUE TITLE
Wrong tooltip for units

### ISSUE THREAD

**Issue by ArminDeeg** [4d/4D-WritePro-Interface#18]
Wrong tooltip for the units popup

<img width="757" alt="Bildschirmfoto 2023-01-19 um 16 00 49" src="https://user-images.githubusercontent.com/6436037/213476942-85070e68-eb25-488b-a708-5b0d4f3daf50.png">

**Comment by ArminDeeg** [comment]
Missing tooltips for the stylsheet options

<img width="203" alt="Bildschirmfoto 2023-01-19 um 16 00 25" src="https://user-images.githubusercontent.com/6436037/213477284-11b55949-8183-48af-a67a-f983601867f8.png">

**Comment by ArminDeeg** [comment]
Missing standard action to show the invisible pictures.

<img width="286" alt="Bildschirmfoto 2023-01-19 um 15 59 25" src="https://user-images.githubusercontent.com/6436037/213477498-a936eee5-435e-47e1-ba00-4220c6d5a5f4.png">

**Comment by ArminDeeg** [comment]
missing tooltip for the print settings icon

<img width="234" alt="Bildschirmfoto 2023-01-19 um 16 06 29" src="https://user-images.githubusercontent.com/6436037/213477922-fe692684-fa03-4c54-9079-4ac4d7997786.png">

**Comment by ArminDeeg** [comment]
Text should be "Nichts"

<img width="533" alt="Bildschirmfoto 2023-01-19 um 16 30 38" src="https://user-images.githubusercontent.com/6436037/213483956-24c39837-f1d9-4f76-bd43-70b894a21056.png">

**Comment by balzercomp** [comment]
Wouldn't it be better "Keine Änderung" oder "Wie eingegeben"?
